export const TASK_STATUS = {
  OPEN: 'open',
  ACCEPTED: 'accepted',
  RUNNING: 'running',
  CONFIRMING: 'confirming',
  FINISHED: 'finished',
  APPEALING: 'appealing',
  RESOLVED: 'resolved',
  CANCELLED: 'cancelled',
  REMOVED: 'removed'
};

export const ORDER_STATUS = {
  OPEN_WAITING: 'open_waiting',
  ACCEPTED: TASK_STATUS.ACCEPTED,
  RUNNING: TASK_STATUS.RUNNING,
  CONFIRMING: TASK_STATUS.CONFIRMING,
  FINISHED: TASK_STATUS.FINISHED,
  APPEALING: TASK_STATUS.APPEALING,
  RESOLVED: TASK_STATUS.RESOLVED,
  CANCELLED: TASK_STATUS.CANCELLED
};

export const TASK_STATUS_LABELS = {
  [TASK_STATUS.OPEN]: '待接单',
  [TASK_STATUS.ACCEPTED]: '已接单',
  [TASK_STATUS.RUNNING]: '进行中',
  [TASK_STATUS.CONFIRMING]: '待确认',
  [TASK_STATUS.FINISHED]: '已完成',
  [TASK_STATUS.APPEALING]: '申诉中',
  [TASK_STATUS.RESOLVED]: '已解决',
  [TASK_STATUS.CANCELLED]: '已取消',
  [TASK_STATUS.REMOVED]: '已删除'
};

export const TASK_STATUS_COLORS = {
  [TASK_STATUS.OPEN]: '#f59e0b',
  [TASK_STATUS.ACCEPTED]: '#2563eb',
  [TASK_STATUS.RUNNING]: '#2563eb',
  [TASK_STATUS.CONFIRMING]: '#8b5cf6',
  [TASK_STATUS.FINISHED]: '#10b981',
  [TASK_STATUS.APPEALING]: '#ef4444',
  [TASK_STATUS.RESOLVED]: '#0f766e',
  [TASK_STATUS.CANCELLED]: '#64748b',
  [TASK_STATUS.REMOVED]: '#dc2626'
};

export const ORDER_STATUS_LABELS = {
  [ORDER_STATUS.OPEN_WAITING]: '待接单',
  [ORDER_STATUS.ACCEPTED]: TASK_STATUS_LABELS[TASK_STATUS.ACCEPTED],
  [ORDER_STATUS.RUNNING]: TASK_STATUS_LABELS[TASK_STATUS.RUNNING],
  [ORDER_STATUS.CONFIRMING]: TASK_STATUS_LABELS[TASK_STATUS.CONFIRMING],
  [ORDER_STATUS.FINISHED]: TASK_STATUS_LABELS[TASK_STATUS.FINISHED],
  [ORDER_STATUS.APPEALING]: TASK_STATUS_LABELS[TASK_STATUS.APPEALING],
  [ORDER_STATUS.RESOLVED]: TASK_STATUS_LABELS[TASK_STATUS.RESOLVED],
  [ORDER_STATUS.CANCELLED]: TASK_STATUS_LABELS[TASK_STATUS.CANCELLED]
};

export const ORDER_STATUS_COLORS = {
  [ORDER_STATUS.OPEN_WAITING]: '#f59e0b',
  [ORDER_STATUS.ACCEPTED]: '#2563eb',
  [ORDER_STATUS.RUNNING]: '#2563eb',
  [ORDER_STATUS.CONFIRMING]: '#8b5cf6',
  [ORDER_STATUS.FINISHED]: '#10b981',
  [ORDER_STATUS.APPEALING]: '#ef4444',
  [ORDER_STATUS.RESOLVED]: '#0f766e',
  [ORDER_STATUS.CANCELLED]: '#64748b'
};

export const TASK_PROGRESS_STEPS = [
  TASK_STATUS.ACCEPTED,
  TASK_STATUS.RUNNING,
  TASK_STATUS.CONFIRMING,
  TASK_STATUS.FINISHED
];

export const CHAT_ENABLED_TASK_STATUSES = [
  TASK_STATUS.ACCEPTED,
  TASK_STATUS.RUNNING,
  TASK_STATUS.CONFIRMING,
  TASK_STATUS.FINISHED,
  TASK_STATUS.APPEALING,
  TASK_STATUS.RESOLVED
];

export function canStartChatForTask(task) {
  return Boolean(task?.runnerId) && CHAT_ENABLED_TASK_STATUSES.includes(task.status);
}
