export const TASK_STATUS = {
  OPEN: 'open',
  ACCEPTED: 'accepted',
  RUNNING: 'running',
  CONFIRMING: 'confirming',
  FINISHED: 'finished',
  APPEALING: 'appealing',
  RESOLVED: 'resolved',
  CANCELLED: 'cancelled',
  REMOVED: 'removed'
};

export const ORDER_STATUS = {
  OPEN_WAITING: 'open_waiting',
  ACCEPTED: TASK_STATUS.ACCEPTED,
  RUNNING: TASK_STATUS.RUNNING,
  CONFIRMING: TASK_STATUS.CONFIRMING,
  FINISHED: TASK_STATUS.FINISHED,
  APPEALING: TASK_STATUS.APPEALING,
  RESOLVED: TASK_STATUS.RESOLVED,
  CANCELLED: TASK_STATUS.CANCELLED
};

export const TASK_ALLOWED_TRANSITIONS = {
  [TASK_STATUS.ACCEPTED]: [TASK_STATUS.RUNNING],
  [TASK_STATUS.RUNNING]: [TASK_STATUS.CONFIRMING],
  [TASK_STATUS.CONFIRMING]: [TASK_STATUS.FINISHED]
};

export const RUNNER_ONLY_NEXT_STATUSES = [TASK_STATUS.RUNNING, TASK_STATUS.CONFIRMING];
export const PUBLISHER_ONLY_NEXT_STATUSES = [TASK_STATUS.FINISHED];
export const TASK_PROGRESS_STEPS = [
  TASK_STATUS.ACCEPTED,
  TASK_STATUS.RUNNING,
  TASK_STATUS.CONFIRMING,
  TASK_STATUS.FINISHED
];
export const APPEALABLE_TASK_STATUSES = [
  TASK_STATUS.ACCEPTED,
  TASK_STATUS.RUNNING,
  TASK_STATUS.CONFIRMING,
  TASK_STATUS.FINISHED
];
export const CHAT_ENABLED_TASK_STATUSES = [
  TASK_STATUS.ACCEPTED,
  TASK_STATUS.RUNNING,
  TASK_STATUS.CONFIRMING,
  TASK_STATUS.FINISHED,
  TASK_STATUS.APPEALING,
  TASK_STATUS.RESOLVED
];

export function canAppealTaskStatus(status) {
  return APPEALABLE_TASK_STATUSES.includes(status);
}

export function canStartChatForTask(task) {
  return Boolean(task?.runnerId) && CHAT_ENABLED_TASK_STATUSES.includes(task.status);
}
